// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SpaceDC.Data;

#nullable disable

namespace SpaceDC.Data.Migrations;

[DbContext(typeof(AppDbContext))]
partial class AppDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.11")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("SpaceDC.Models.Booking", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<DateTimeOffset>("EndTime")
                    .HasColumnType("timestamp with time zone");

                b.Property<Guid>("ResourceId")
                    .HasColumnType("uuid");

                b.Property<DateTimeOffset>("StartTime")
                    .HasColumnType("timestamp with time zone");

                b.Property<int>("Status")
                    .HasColumnType("integer");

                b.Property<Guid>("UserId")
                    .HasColumnType("uuid");

                b.HasKey("Id");

                b.HasIndex("UserId");

                b.HasIndex("ResourceId", "StartTime", "EndTime");

                b.ToTable("bookings", (string)null);
            });

        modelBuilder.Entity("SpaceDC.Models.Resource", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<int>("Capacity")
                    .HasColumnType("integer");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)");

                b.Property<int>("Status")
                    .HasColumnType("integer");

                b.Property<int>("Type")
                    .HasColumnType("integer");

                b.HasKey("Id");

                b.ToTable("resources", (string)null);
            });

        modelBuilder.Entity("SpaceDC.Models.ResourceSchedule", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<int>("DayOfWeek")
                    .HasColumnType("integer");

                b.Property<TimeOnly>("EndTime")
                    .HasColumnType("time without time zone");

                b.Property<Guid>("ResourceId")
                    .HasColumnType("uuid");

                b.Property<TimeOnly>("StartTime")
                    .HasColumnType("time without time zone");

                b.HasKey("Id");

                b.HasIndex("ResourceId", "DayOfWeek");

                b.ToTable("resource_schedules", (string)null);
            });

        modelBuilder.Entity("SpaceDC.Models.User", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasMaxLength(320)
                    .HasColumnType("character varying(320)");

                b.Property<string>("PasswordHash")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<int>("Role")
                    .HasColumnType("integer");

                b.HasKey("Id");

                b.HasIndex("Email")
                    .IsUnique();

                b.ToTable("users", (string)null);
            });

        modelBuilder.Entity("SpaceDC.Models.Booking", b =>
            {
                b.HasOne("SpaceDC.Models.Resource", "Resource")
                    .WithMany("Bookings")
                    .HasForeignKey("ResourceId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("SpaceDC.Models.User", "User")
                    .WithMany("Bookings")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("Resource");

                b.Navigation("User");
            });

        modelBuilder.Entity("SpaceDC.Models.ResourceSchedule", b =>
            {
                b.HasOne("SpaceDC.Models.Resource", "Resource")
                    .WithMany("Schedules")
                    .HasForeignKey("ResourceId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Resource");
            });

        modelBuilder.Entity("SpaceDC.Models.Resource", b =>
            {
                b.Navigation("Bookings");

                b.Navigation("Schedules");
            });

        modelBuilder.Entity("SpaceDC.Models.User", b =>
            {
                b.Navigation("Bookings");
            });
#pragma warning restore 612, 618
    }
}
